### ISSUE TITLE
Should check nodejs version in run.js

### ISSUE THREAD

**Issue by syntrust** [ethstorage/es-node#256]
# Rationale
Old version fails to gen proof which is a waste:
```
Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/snarkjs/node_modules/web-worker/cjs/node.js:20:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
# Implementation

check nodejs version in run.js

**Comment by syntrust** [comment]
Done with https://github.com/ethstorage/es-node/pull/272
